categories_and_channels:
  type: list
  default: ""
  description:
    en: "List of the secure categories and chat channels to hide the lock badge icon for. 
    Must be in semi-colon delimited format with category-slug;category-ID. Channel slug name must be same as respective category slug name.<br>
    (For example: staff;3 or off-topic;5)"
