categories:
  type: list
  default: ""
  description:
    en: "List the secure categories to hide the lock badge icon for."

category_drop_down:
  type: bool
  default: false
  description:
    en: "Hide the lock icon badge for secure categories in the category breadcrumb drop down selector."

navigation_menu:
  type: bool
  default: false
  description:
    en: "Hide the lock icon badge for secure categories in the category section of the navigation sidebar menu."

category_header_breadcrumb:
  type: bool
  default: false
  description:
    en: "Hide the lock icon badge for secure categories in the category section of the navigation sidebar menu."
